preset: recommended                                                                                                                                                                          

risky: true

enabled:
  - short_array_syntax
  - align_double_arrow

disabled:
  - long_array_syntax
  - psr4

finder:
  name: [ "*.php"]
  exclude : [ "vendor"]
